project_id = "pfsmikupgqyezsroqigf"

[functions.send-invite]
verify_jwt = true

[functions.zapi-webhook]
verify_jwt = false

[functions.manage-tenant]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true
